homepage:
    pattern:  /
    defaults: { _controller: FrameworkBundle:Default:index }

hello:
    resource: HelloBundle/Resources/config/routing.yml
    
ariadne:
    resource: Ariadne/AriadneBundle/Resources/config/routing.yml
